<?php

$event = static function (
    string $module,
    string $title,
    string $description,
    string $severity,
    string $analysisHint
): array {
    return [
        'module' => $module,
        'title' => $title,
        'description' => $description,
        'severity' => $severity,
        'analysis_hint' => $analysisHint,
    ];
};

return [
    'auth.login_success' => $event('Autenticacion', 'Inicio de sesion exitoso', 'Un usuario inicio sesion correctamente.', 'success', 'Verificar que IP, navegador y horario correspondan al patron esperado.'),
    'auth.login_failed' => $event('Autenticacion', 'Inicio de sesion fallido', 'Un usuario intento iniciar sesion sin completar la autenticacion.', 'warning', 'Revisar multiples intentos sobre el mismo usuario o desde la misma IP.'),
    'auth.logout' => $event('Autenticacion', 'Cierre de sesion', 'Un usuario cerro su sesion.', 'info', 'Normalmente no requiere accion salvo que ocurra tras actividad sospechosa.'),
    'auth.domain_denied' => $event('Autenticacion', 'Dominio no autorizado', 'Se rechazo un acceso por restriccion de dominio.', 'warning', 'Confirmar si el dominio usado debe estar permitido.'),
    'auth.user_inactive' => $event('Autenticacion', 'Usuario inactivo intento acceder', 'Una cuenta inactiva intento iniciar sesion.', 'warning', 'Validar si la cuenta debe reactivarse o si el intento fue inesperado.'),
    'auth.user_blocked' => $event('Autenticacion', 'Usuario bloqueado intento acceder', 'Una cuenta bloqueada intento iniciar sesion.', 'warning', 'Revisar motivo del bloqueo y origen del intento.'),
    'auth.account_locked' => $event('Autenticacion', 'Cuenta bloqueada', 'La cuenta fue bloqueada por politica de seguridad.', 'critical', 'Investigar intentos fallidos recientes y confirmar con el usuario.'),
    'auth.local_login_disabled' => $event('Autenticacion', 'Login local deshabilitado', 'Se intento iniciar sesion con credenciales locales cuando el login local estaba deshabilitado por configuracion.', 'warning', 'Revisar configuracion de autenticacion, metodos externos habilitados y posibles intentos de acceso por un metodo no permitido.'),
    'auth.session_locked' => $event('Autenticacion', 'Sesion bloqueada por inactividad', 'La sesion fue bloqueada por inactividad.', 'info', 'Normalmente no requiere accion salvo que ocurra durante actividad sospechosa.'),
    'auth.session_unlocked' => $event('Autenticacion', 'Sesion desbloqueada', 'El usuario desbloqueo su sesion por inactividad.', 'success', 'Revisar solo si hay intentos fallidos previos.'),
    'auth.session_unlock_failed' => $event('Autenticacion', 'Desbloqueo de sesion fallido', 'Fallo el desbloqueo de una sesion bloqueada.', 'warning', 'Revisar intentos repetidos o IP inusual.'),
    'auth.session_unlock_rate_limited' => $event('Autenticacion', 'Desbloqueo de sesion bloqueado temporalmente', 'Se alcanzo o se intento superar el limite de intentos de desbloqueo de sesion.', 'warning', 'Revisar usuario, recurrencia y posibles intentos de acceso fisico o sesion desatendida.'),
    'security.access_denied' => $event('Seguridad', 'Acceso denegado', 'Un usuario intento acceder a una ruta sin permiso suficiente.', 'warning', 'Revisar ruta solicitada, permiso requerido y recurrencia del evento.'),

    'external_login.started' => $event('OAuth', 'Inicio de login externo', 'Se inicio un flujo de autenticacion externa.', 'info', 'Confirmar que el proveedor y origen sean esperados.'),
    'external_login.success' => $event('OAuth', 'Login externo exitoso', 'Un usuario ingreso mediante proveedor externo.', 'success', 'Validar IP, proveedor y correo asociado si hay dudas.'),
    'external_login.failed' => $event('OAuth', 'Login externo fallido', 'Fallo un intento de autenticacion externa.', 'warning', 'Revisar proveedor, dominio y errores relacionados.'),
    'external_login.denied' => $event('OAuth', 'Login externo denegado', 'El acceso externo fue rechazado por reglas del sistema.', 'warning', 'Confirmar si el usuario o proveedor deben estar autorizados.'),
    'external_login.provider_disabled' => $event('OAuth', 'Proveedor externo deshabilitado', 'Se intento iniciar sesion usando un proveedor externo deshabilitado o no disponible.', 'warning', 'Revisar configuracion del proveedor, estado activo y posibles intentos de acceso por rutas no disponibles.'),
    'external_login.email_not_verified' => $event('OAuth', 'Correo externo no verificado', 'El proveedor externo no confirmo el correo como verificado y se rechazo el inicio de sesion.', 'warning', 'Revisar proveedor, datos recibidos y configuracion de seguridad para correos no verificados.'),
    'external_login.user_not_found' => $event('OAuth', 'Usuario externo no encontrado', 'El login externo fue rechazado porque no existe una cuenta local asociada y la creacion automatica no esta habilitada.', 'warning', 'Revisar configuracion de enlace automatico, creacion de usuarios y dominio permitido.'),
    'external_login.auto_user_created' => $event('OAuth', 'Usuario creado automaticamente por login externo', 'Se creo automaticamente una cuenta local a partir de un inicio de sesion externo permitido.', 'info', 'Revisar dominio, proveedor utilizado y configuracion de creacion automatica de usuarios.'),
    'external_login.invalid_state' => $event('OAuth', 'State OAuth invalido', 'El flujo externo regreso con un state invalido.', 'critical', 'Puede indicar expiracion, replay o manipulacion del flujo OAuth.'),
    'external_login.domain_denied' => $event('OAuth', 'Dominio externo denegado', 'El correo externo no cumple la restriccion de dominio.', 'warning', 'Validar dominios permitidos y origen del intento.'),
    'external_provider.updated' => $event('OAuth', 'Proveedor externo actualizado', 'Se actualizo la configuracion de un proveedor externo.', 'warning', 'Revisar que no se hayan cambiado endpoints o politicas sin autorizacion.'),
    'external_provider.enabled' => $event('OAuth', 'Proveedor externo activado', 'Se habilito un proveedor de autenticacion externa.', 'warning', 'Confirmar aprobacion administrativa del proveedor.'),
    'external_provider.disabled' => $event('OAuth', 'Proveedor externo desactivado', 'Se deshabilito un proveedor externo.', 'warning', 'Validar impacto sobre usuarios que dependen de ese proveedor.'),
    'external_provider.test_success' => $event('OAuth', 'Prueba de proveedor exitosa', 'La prueba de configuracion del proveedor externo fue exitosa.', 'success', 'No requiere accion salvo documentar el cambio.'),
    'external_provider.test_failed' => $event('OAuth', 'Prueba de proveedor fallida', 'La prueba de configuracion del proveedor externo fallo.', 'warning', 'Revisar configuracion sin exponer secretos.'),
    'external_provider.test_rate_limited' => $event('OAuth', 'Prueba de proveedor OAuth limitada temporalmente', 'Se bloqueo temporalmente una prueba administrativa de proveedor OAuth por exceso de intentos.', 'warning', 'Revisar recurrencia, usuario administrador, proveedor y posible abuso o automatizacion accidental.'),
    'external_provider.verified' => $event('OAuth', 'Proveedor verificado', 'El proveedor externo quedo marcado como verificado.', 'success', 'Confirmar que la verificacion fue realizada por personal autorizado.'),
    'external_provider.unverified' => $event('OAuth', 'Proveedor no verificado', 'El proveedor externo quedo sin verificacion.', 'warning', 'Revisar si debe quedar habilitado.'),

    'users.created' => $event('Usuarios', 'Usuario creado', 'Se creo una cuenta de usuario.', 'success', 'Verificar rol asignado y correo del usuario creado.'),
    'users.updated' => $event('Usuarios', 'Usuario actualizado', 'Se modificaron datos de un usuario.', 'info', 'Revisar cambios de rol, estado o datos de contacto.'),
    'users.deleted' => $event('Usuarios', 'Usuario eliminado o inactivado', 'Se elimino o inactivo una cuenta de usuario.', 'warning', 'Confirmar que la accion fue solicitada y autorizada.'),
    'users.activated' => $event('Usuarios', 'Usuario activado', 'Se activo una cuenta de usuario.', 'success', 'Verificar que la reactivacion corresponda a una solicitud valida.'),
    'users.deactivated' => $event('Usuarios', 'Usuario desactivado', 'Se desactivo una cuenta de usuario.', 'warning', 'Confirmar si existen accesos recientes que requieran revision.'),
    'users.locked' => $event('Usuarios', 'Usuario bloqueado', 'Una cuenta fue bloqueada.', 'warning', 'Revisar causa del bloqueo y actividad previa.'),
    'users.unlocked' => $event('Usuarios', 'Usuario desbloqueado', 'Una cuenta fue desbloqueada.', 'warning', 'Confirmar identidad del solicitante antes del desbloqueo.'),
    'users.role_changed' => $event('Usuarios', 'Rol de usuario cambiado', 'Se modifico el rol asignado a un usuario.', 'critical', 'Revisar si el cambio aumento privilegios.'),
    'users.password_changed_by_admin' => $event('Usuarios', 'Contrasena cambiada por administrador', 'Un administrador cambio la contrasena de un usuario.', 'critical', 'Confirmar solicitud y verificar cierre de sesiones previas.'),
    'users.force_password_change_enabled' => $event('Usuarios', 'Cambio obligatorio activado', 'Se activo el cambio obligatorio de contrasena para un usuario.', 'warning', 'Validar motivo de seguridad o cumplimiento.'),
    'users.force_password_change_disabled' => $event('Usuarios', 'Cambio obligatorio desactivado', 'Se desactivo el cambio obligatorio de contrasena.', 'warning', 'Confirmar que el usuario ya cumplio la politica requerida.'),
    'users.exported' => $event('Usuarios', 'Usuarios exportados', 'Se exporto informacion del listado de usuarios.', 'warning', 'Verificar que el exportador tenga autorizacion y uso legitimo.'),
    'users.export_failed' => $event('Usuarios', 'Exportacion de usuarios fallida', 'No se pudo exportar el listado de usuarios.', 'warning', 'Revisar logs tecnicos y filtros aplicados.'),
    'users.create_failed' => $event('Usuarios', 'Creacion de usuario fallida', 'No se pudo crear un usuario.', 'warning', 'Revisar validaciones y datos enviados.'),
    'users.update_failed' => $event('Usuarios', 'Actualizacion de usuario fallida', 'No se pudo actualizar un usuario.', 'warning', 'Revisar validaciones y logs tecnicos.'),

    'profile.updated' => $event('Cuenta', 'Perfil actualizado', 'El usuario actualizo datos de su perfil.', 'info', 'Revisar solo si ocurre junto con otros eventos sospechosos.'),
    'profile.avatar_updated' => $event('Cuenta', 'Avatar actualizado', 'El usuario actualizo su imagen de perfil.', 'info', 'Normalmente no requiere accion.'),
    'profile.theme_updated' => $event('Cuenta', 'Tema actualizado', 'El usuario cambio su preferencia visual.', 'info', 'No requiere accion.'),
    'profile.preferences_updated' => $event('Cuenta', 'Preferencias actualizadas', 'El usuario actualizo preferencias de su cuenta.', 'info', 'Normalmente no requiere accion.'),
    'account.password_changed' => $event('Cuenta', 'Contrasena propia cambiada', 'El usuario cambio su propia contrasena.', 'critical', 'Confirmar que otras sesiones hayan sido cerradas y revisar accesos recientes.'),
    'account.password_change_failed' => $event('Cuenta', 'Cambio de contrasena fallido', 'Fallo el cambio de contrasena del usuario.', 'warning', 'Revisar intentos repetidos o incumplimiento de politica.'),
    'account.email_change_requested' => $event('Cuenta', 'Cambio de correo solicitado', 'El usuario inicio un cambio de correo.', 'warning', 'Verificar si la solicitud fue esperada.'),
    'account.email_change_code_sent' => $event('Cuenta', 'Codigo de correo enviado', 'Se envio codigo para cambio de correo.', 'info', 'No registrar ni solicitar el codigo al usuario.'),
    'account.email_change_code_resent' => $event('Cuenta', 'Codigo de correo reenviado', 'Se reenvio codigo para cambio de correo.', 'info', 'Revisar repeticion excesiva.'),
    'account.email_change_failed' => $event('Cuenta', 'Cambio de correo fallido', 'Fallo la validacion del cambio de correo.', 'warning', 'Revisar intentos repetidos o codigos vencidos.'),
    'account.email_change_completed' => $event('Cuenta', 'Cambio de correo completado', 'El correo del usuario fue actualizado.', 'critical', 'Confirmar que el nuevo correo pertenece al usuario y que se cerraron otras sesiones.'),
    'account.email_change_cancelled' => $event('Cuenta', 'Cambio de correo cancelado', 'El usuario cancelo el cambio de correo pendiente.', 'info', 'Normalmente no requiere accion.'),

    'password_reset.requested' => $event('Recuperacion de contrasena', 'Recuperacion solicitada', 'Se solicito restablecer una contrasena.', 'warning', 'Revisar frecuencia por correo o IP.'),
    'password_reset.email_sent' => $event('Recuperacion de contrasena', 'Correo de recuperacion enviado', 'Se envio el correo de restablecimiento.', 'info', 'No registrar ni exponer tokens.'),
    'password_reset.email_failed' => $event('Recuperacion de contrasena', 'Error al enviar correo de recuperacion', 'No fue posible enviar el correo de recuperacion de contrasena al usuario.', 'warning', 'Revisar configuracion SMTP, estado del usuario, dominio del correo y logs tecnicos del envio.'),
    'password_reset.token_invalid' => $event('Recuperacion de contrasena', 'Token invalido', 'Se uso un token de recuperacion invalido.', 'warning', 'Revisar intentos repetidos.'),
    'password_reset.token_expired' => $event('Recuperacion de contrasena', 'Token vencido', 'Se uso un token de recuperacion vencido.', 'info', 'Puede ser normal si el usuario tardo demasiado.'),
    'password_reset.policy_validation_failed' => $event('Recuperacion de contrasena', 'Politica de contrasena no cumplida', 'La nueva contrasena no cumple la politica de seguridad configurada.', 'warning', 'Revisar la politica activa y los errores de validacion reportados al usuario.'),
    'password_reset.history_reuse_blocked' => $event('Recuperacion de contrasena', 'Reutilizacion de contrasena bloqueada', 'Se bloqueo el cambio de contrasena porque la nueva contrasena coincide con una contrasena usada recientemente.', 'warning', 'Revisar politica de historial de contrasenas y orientar al usuario para definir una contrasena distinta.'),
    'password_reset.completed' => $event('Recuperacion de contrasena', 'Recuperacion completada', 'La contrasena fue actualizada por recuperacion.', 'critical', 'Confirmar cierre de sesiones anteriores.'),
    'password_reset.domain_denied' => $event('Recuperacion de contrasena', 'Dominio denegado en recuperacion', 'Se rechazo recuperacion por dominio no permitido.', 'warning', 'Validar si el dominio debe estar autorizado.'),
    'password_reset.ip_rate_limited' => $event('Recuperacion de contrasena', 'Recuperacion limitada por IP', 'Se alcanzo o se intento superar el limite de solicitudes de recuperacion de contrasena desde la misma IP.', 'warning', 'Revisar recurrencia, IP, volumen de solicitudes y posible abuso.'),
    'password_reset.rate_limited' => $event('Recuperacion de contrasena', 'Recuperacion limitada por correo', 'Se alcanzo el limite de solicitudes de recuperacion de contrasena para el mismo correo dentro de la ventana configurada.', 'warning', 'Revisar recurrencia, volumen de solicitudes, posible abuso o usuario olvidando su contrasena.'),
    'password_reset.failed' => $event('Recuperacion de contrasena', 'Recuperacion fallida', 'Fallo el proceso de recuperacion.', 'warning', 'Revisar motivo y frecuencia.'),

    'smtp.updated' => $event('SMTP', 'SMTP actualizado', 'Se actualizo la configuracion SMTP.', 'critical', 'Revisar que no se hayan cambiado servidores o remitentes sin autorizacion.'),
    'smtp.test_success' => $event('SMTP', 'Prueba SMTP exitosa', 'La prueba de envio SMTP fue exitosa.', 'success', 'No requiere accion salvo documentar cambios.'),
    'smtp.test_failed' => $event('SMTP', 'Prueba SMTP fallida', 'La prueba SMTP fallo.', 'warning', 'Revisar configuracion sin exponer contrasenas.'),
    'smtp.test_rate_limited' => $event('SMTP', 'Prueba SMTP limitada temporalmente', 'Se bloqueo temporalmente una prueba SMTP por exceso de intentos.', 'warning', 'Revisar recurrencia, usuario administrador y posible automatizacion accidental.'),
    'smtp.update_failed' => $event('SMTP', 'Actualizacion SMTP fallida', 'No se pudo guardar la configuracion SMTP.', 'warning', 'Revisar logs tecnicos y permisos.'),

    'mfa.settings_updated' => $event('MFA', 'Configuracion MFA actualizada', 'Se actualizo la configuracion global de MFA.', 'critical', 'Confirmar aprobacion porque afecta el nivel de seguridad de acceso.'),
    'mfa.method_enabled' => $event('MFA', 'Metodo MFA activado', 'Se activo un metodo MFA.', 'warning', 'Verificar metodo y alcance del cambio.'),
    'mfa.method_disabled' => $event('MFA', 'Metodo MFA desactivado', 'Se desactivo un metodo MFA.', 'critical', 'Revisar impacto sobre seguridad de acceso.'),
    'mfa.user_enabled' => $event('MFA', 'MFA de usuario activado', 'Un usuario activo MFA en su cuenta.', 'success', 'Confirmar cierre de otras sesiones si aplica.'),
    'mfa.user_enable_failed' => $event('MFA', 'Error al habilitar MFA de usuario', 'No fue posible habilitar MFA para el usuario.', 'warning', 'Revisar metodo MFA, datos enviados, estado del usuario y logs tecnicos asociados.'),
    'mfa.user_disabled' => $event('MFA', 'MFA de usuario desactivado', 'Un usuario desactivo MFA en su cuenta.', 'critical', 'Revisar si fue una accion esperada.'),
    'mfa.challenge_success' => $event('MFA', 'Verificacion MFA exitosa', 'El usuario completo el desafio MFA.', 'success', 'Revisar solo si hay actividad inusual.'),
    'mfa.challenge_failed' => $event('MFA', 'Verificacion MFA fallida', 'Fallo un desafio MFA.', 'warning', 'Revisar intentos repetidos o desde ubicaciones inusuales.'),
    'mfa.totp_rate_limited' => $event('MFA', 'Verificacion TOTP bloqueada temporalmente', 'Se alcanzo o se intento superar el limite de intentos de verificacion TOTP.', 'warning', 'Revisar usuario, recurrencia y posibles intentos de fuerza bruta.'),
    'mfa.challenge_required' => $event('MFA', 'Desafio MFA requerido', 'El sistema solicito validacion MFA para completar el acceso.', 'info', 'Normal si el usuario tiene MFA activo.'),
    'mfa.method_unavailable' => $event('MFA', 'Metodo MFA no disponible', 'El metodo MFA esperado no estaba disponible.', 'warning', 'Revisar configuracion MFA del usuario y metodos habilitados.'),
    'mfa.reset_by_admin' => $event('MFA', 'MFA reiniciado por administrador', 'Un administrador reinicio o desactivo MFA de un usuario.', 'critical', 'Confirmar solicitud y cierre de sesiones del usuario afectado.'),

    'login_attempts.settings_updated' => $event('Intentos fallidos', 'Politica de intentos actualizada', 'Se actualizo la configuracion de intentos fallidos.', 'warning', 'Confirmar que los umbrales sean adecuados.'),
    'login_attempts.user_locked' => $event('Intentos fallidos', 'Usuario bloqueado por intentos', 'Un usuario fue bloqueado por intentos fallidos.', 'critical', 'Investigar posible fuerza bruta o credenciales comprometidas.'),
    'login_attempts.ip_locked' => $event('Intentos fallidos', 'IP bloqueada', 'Una IP fue bloqueada por intentos fallidos.', 'critical', 'Revisar origen y volumen de intentos.'),
    'login_attempts.user_unlocked' => $event('Intentos fallidos', 'Usuario desbloqueado', 'Se limpio o levanto bloqueo por intentos.', 'warning', 'Confirmar identidad del solicitante.'),
    'login_attempts.cleared' => $event('Intentos fallidos', 'Intentos limpiados', 'Se limpiaron registros de intentos fallidos.', 'warning', 'Verificar motivo operativo.'),

    'authentication.settings_updated' => $event('Autenticacion', 'Configuracion de autenticacion actualizada', 'Se cambio la configuracion general de autenticacion.', 'critical', 'Revisar cambios sobre login local, OAuth y dominios permitidos.'),
    'authentication.settings_update_failed' => $event('Autenticacion', 'Error al actualizar configuracion de autenticacion', 'No fue posible guardar la configuracion de autenticacion del sistema, por ejemplo por no cumplir una validacion requerida.', 'warning', 'Revisar validaciones, permisos, parametros enviados y logs tecnicos asociados.'),
    'authentication.local_login_enabled' => $event('Autenticacion', 'Login local activado', 'Se habilito el login local.', 'warning', 'Confirmar politica de autenticacion vigente.'),
    'authentication.local_login_disabled' => $event('Autenticacion', 'Login local desactivado', 'Se deshabilito el login local.', 'warning', 'Verificar que existan metodos alternos disponibles.'),
    'authentication.external_login_enabled' => $event('Autenticacion', 'Login externo activado', 'Se habilito autenticacion externa.', 'warning', 'Confirmar proveedores y dominios permitidos.'),
    'authentication.external_login_disabled' => $event('Autenticacion', 'Login externo desactivado', 'Se deshabilito autenticacion externa.', 'warning', 'Validar impacto operativo.'),
    'authentication.domain_restriction_updated' => $event('Autenticacion', 'Restriccion de dominio actualizada', 'Se actualizo la restriccion por dominio.', 'critical', 'Revisar si se ampliaron dominios permitidos.'),
    'authentication.allowed_domains_updated' => $event('Autenticacion', 'Dominios autorizados actualizados', 'Se modifico la lista de dominios autorizados.', 'critical', 'Confirmar cada dominio agregado o removido.'),
    'authentication.auto_user_creation_updated' => $event('Autenticacion', 'Creacion automatica actualizada', 'Se cambio la regla de creacion automatica de usuarios.', 'critical', 'Validar riesgo de aprovisionamiento no autorizado.'),
    'authentication.require_existing_user_updated' => $event('Autenticacion', 'Requerir usuario existente actualizado', 'Se cambio la regla que exige usuario existente.', 'critical', 'Revisar impacto sobre altas por OAuth.'),
    'authentication.auto_link_updated' => $event('Autenticacion', 'Vinculacion automatica actualizada', 'Se cambio la vinculacion automatica de cuentas externas.', 'critical', 'Revisar riesgo de vinculaciones no deseadas.'),

    'security_sessions.settings_updated' => $event('Sesiones', 'Configuracion de sesiones actualizada', 'Se actualizo la configuracion de bloqueo o sesiones.', 'warning', 'Confirmar tiempos de inactividad y alcance del cambio.'),

    'password_policy.updated' => $event('Politica de contrasenas', 'Politica actualizada', 'Se actualizo la politica de contrasenas.', 'critical', 'Confirmar aprobacion y parametros aplicados.'),
    'password_policy.validation_failed' => $event('Politica de contrasenas', 'Validacion de politica fallida', 'Una contrasena propuesta no cumplio la politica.', 'info', 'No requiere accion salvo repeticion inusual.'),
    'password_policy.history_reuse_blocked' => $event('Politica de contrasenas', 'Reutilizacion bloqueada', 'Se bloqueo reutilizacion de contrasena anterior.', 'warning', 'Indica intento de usar credenciales antiguas.'),
    'password.expired' => $event('Politica de contrasenas', 'Contrasena vencida', 'La contrasena del usuario vencio.', 'info', 'Debe completarse cambio obligatorio.'),
    'password.required_change_redirected' => $event('Politica de contrasenas', 'Redireccion a cambio obligatorio', 'El usuario fue enviado a cambiar contrasena obligatoriamente.', 'info', 'Verificar que complete el cambio.'),
    'password.required_change_completed' => $event('Politica de contrasenas', 'Cambio obligatorio completado', 'El usuario completo el cambio obligatorio de contrasena.', 'success', 'Confirmar cierre de otras sesiones si aplica.'),

    'roles.created' => $event('Roles y permisos', 'Rol creado', 'Se creo un rol.', 'warning', 'Revisar permisos asignados al rol nuevo.'),
    'roles.updated' => $event('Roles y permisos', 'Rol actualizado', 'Se modifico un rol.', 'warning', 'Validar cambios de alcance.'),
    'roles.deleted' => $event('Roles y permisos', 'Rol eliminado', 'Se elimino un rol.', 'warning', 'Confirmar que no afecte usuarios activos.'),
    'roles.permissions_updated' => $event('Roles y permisos', 'Permisos de rol actualizados', 'Se modifico el conjunto de permisos de un rol.', 'critical', 'Revisar permisos agregados o removidos, especialmente administrativos.'),
    'permissions.assigned' => $event('Roles y permisos', 'Permiso asignado', 'Se asigno un permiso.', 'critical', 'Confirmar si eleva privilegios.'),
    'permissions.removed' => $event('Roles y permisos', 'Permiso removido', 'Se removio un permiso.', 'warning', 'Validar impacto operativo.'),
    'permissions.denied' => $event('Roles y permisos', 'Permiso denegado', 'Se denego acceso por falta de permiso.', 'warning', 'Revisar ruta y usuario afectado.'),
    'permissions.admin_role_protected' => $event('Roles y permisos', 'Rol administrador protegido', 'Se intento modificar un rol protegido.', 'critical', 'Investigar intento de alterar privilegios criticos.'),

    'audit.exported' => $event('Auditoria', 'Auditoria exportada', 'Se exportaron registros de auditoria.', 'critical', 'Verificar filtros usados y motivo de la descarga.'),
    'audit.export_failed' => $event('Auditoria', 'Exportacion de auditoria fallida', 'Fallo la exportacion de auditoria.', 'warning', 'Revisar logs tecnicos.'),
    'audit.access_denied' => $event('Auditoria', 'Acceso a auditoria denegado', 'Se denego acceso al modulo de auditoria.', 'warning', 'Revisar si fue intento manual por URL.'),

    'appearance.updated' => $event('Apariencia', 'Apariencia actualizada', 'Se actualizo configuracion visual del sistema.', 'info', 'Confirmar cambios visibles.'),
    'appearance.logo_updated' => $event('Apariencia', 'Logo actualizado', 'Se actualizo el logo del sistema.', 'info', 'Validar archivo y visualizacion.'),
    'appearance.logo_reset' => $event('Apariencia', 'Logo restablecido', 'Se restablecio el logo.', 'info', 'No requiere accion salvo confirmacion visual.'),
    'appearance.favicon_updated' => $event('Apariencia', 'Favicon actualizado', 'Se actualizo el favicon.', 'info', 'Validar archivo subido.'),
    'appearance.favicon_reset' => $event('Apariencia', 'Favicon restablecido', 'Se restablecio el favicon.', 'info', 'No requiere accion.'),
    'appearance.login_background_updated' => $event('Apariencia', 'Fondo de login actualizado', 'Se actualizo el fondo de login.', 'info', 'Validar archivo y contraste.'),
    'appearance.login_background_reset' => $event('Apariencia', 'Fondo de login restablecido', 'Se restablecio el fondo de login.', 'info', 'No requiere accion.'),
    'appearance.colors_updated' => $event('Apariencia', 'Colores actualizados', 'Se actualizaron colores del sistema.', 'info', 'Validar contraste en modo claro y oscuro.'),
    'appearance.colors_reset' => $event('Apariencia', 'Colores restablecidos', 'Se restablecieron colores del sistema.', 'info', 'No requiere accion.'),

    'manuals.uploaded' => $event('Manuales', 'Manual subido', 'Se subio un manual del sistema.', 'success', 'Verificar archivo y estado publicado.'),
    'manuals.replaced' => $event('Manuales', 'Manual reemplazado', 'Se reemplazo el archivo de un manual.', 'warning', 'Confirmar que la nueva version sea correcta.'),
    'manuals.activated' => $event('Manuales', 'Manual activado', 'Un manual quedo disponible.', 'success', 'Verificar que el archivo sea el correcto.'),
    'manuals.deactivated' => $event('Manuales', 'Manual desactivado', 'Un manual dejo de estar disponible.', 'warning', 'Confirmar motivo de despublicacion.'),
    'manuals.deleted' => $event('Manuales', 'Manual eliminado', 'Se marco o elimino un manual.', 'warning', 'Confirmar que no se requiere conservarlo visible.'),
    'manuals.downloaded' => $event('Manuales', 'Manual descargado', 'Un usuario descargo un manual.', 'info', 'Normalmente no requiere accion.'),
    'manuals.upload_failed' => $event('Manuales', 'Subida de manual fallida', 'No se pudo subir un manual.', 'warning', 'Revisar extension, tamano o permisos.'),
    'manuals.replace_failed' => $event('Manuales', 'Reemplazo de manual fallido', 'No se pudo reemplazar un manual.', 'warning', 'Verificar validaciones del archivo.'),
    'manuals.delete_failed' => $event('Manuales', 'Eliminacion de manual fallida', 'No se pudo eliminar un manual.', 'warning', 'Revisar logs tecnicos.'),

    'export.failed' => $event('Exportaciones', 'Exportacion fallida', 'Fallo una exportacion.', 'warning', 'Revisar modulo, filtros y logs tecnicos.'),
    'export.denied' => $event('Exportaciones', 'Exportacion denegada', 'Se denego una exportacion por permisos.', 'warning', 'Revisar usuario y modulo solicitado.'),

    'sessions.created' => $event('Sesiones', 'Sesion registrada', 'Se registro una sesion activa del usuario.', 'success', 'Verificar solo si aparece en IP o dispositivo inesperado.'),
    'sessions.revoked' => $event('Sesiones', 'Sesion cerrada', 'Una sesion fue revocada.', 'info', 'Revisar motivo de cierre.'),
    'sessions.revoked_by_user' => $event('Sesiones', 'Sesion cerrada por usuario', 'El usuario cerro una de sus sesiones.', 'info', 'No requiere accion salvo actividad inusual.'),
    'sessions.revoked_by_admin' => $event('Sesiones', 'Sesion cerrada por administrador', 'Un administrador cerro una sesion.', 'warning', 'Confirmar motivo operativo o de seguridad.'),
    'sessions.revoked_from_history' => $event('Sesiones', 'Sesion revocada desde historial', 'Se revoco una sesion especifica desde el historial de sesiones.', 'warning', 'Revisar usuario afectado, sesion revocada, administrador que ejecuto la accion y motivo operativo o de seguridad.'),
    'sessions.revoked_others' => $event('Sesiones', 'Otras sesiones cerradas', 'El usuario cerro todas sus demas sesiones.', 'warning', 'Puede indicar saneamiento tras cambio sensible.'),
    'sessions.revoked_all_user' => $event('Sesiones', 'Sesiones de usuario cerradas', 'Se cerraron todas las sesiones activas de un usuario.', 'critical', 'Confirmar solicitud y usuario afectado.'),
    'sessions.revoked_all_from_user_history' => $event('Sesiones', 'Sesiones revocadas desde historial de usuario', 'Se revocaron todas las sesiones activas de un usuario desde su historial de sesiones.', 'warning', 'Revisar usuario afectado, administrador que ejecuto la accion y motivo operativo o de seguridad.'),
    'sessions.revoked_due_password_change' => $event('Sesiones', 'Sesiones cerradas por cambio de contrasena', 'Otras sesiones se cerraron tras cambio de contrasena.', 'critical', 'Confirmar que solo la sesion actual continuo activa.'),
    'sessions.revoked_due_password_reset' => $event('Sesiones', 'Sesiones cerradas por recuperacion', 'Sesiones activas se cerraron tras restablecer contrasena.', 'critical', 'Verificar que el usuario vuelva a iniciar sesion.'),
    'sessions.revoked_due_required_password_change' => $event('Sesiones', 'Sesiones cerradas por cambio obligatorio', 'Otras sesiones se cerraron tras cambio obligatorio de contrasena.', 'critical', 'Confirmar cumplimiento de politica.'),
    'sessions.revoked_due_mfa_change' => $event('Sesiones', 'Sesiones cerradas por cambio MFA', 'Otras sesiones se cerraron tras modificar MFA.', 'critical', 'Revisar si el cambio MFA fue autorizado.'),
    'sessions.revoked_due_email_change' => $event('Sesiones', 'Sesiones cerradas por cambio de correo', 'Otras sesiones se cerraron tras completar cambio de correo.', 'critical', 'Confirmar nuevo correo y actividad posterior.'),
    'sessions.revoked_due_admin_password_change' => $event('Sesiones', 'Sesiones cerradas por contrasena admin', 'Sesiones de un usuario se cerraron por cambio de contrasena administrativo.', 'critical', 'Confirmar solicitud y usuario afectado.'),
    'sessions.revoked_due_force_password_change' => $event('Sesiones', 'Sesiones cerradas por cambio requerido', 'Sesiones se cerraron al exigir cambio de contrasena.', 'critical', 'Confirmar que la accion fue deliberada.'),
    'sessions.revoked_due_admin_mfa_reset' => $event('Sesiones', 'Sesiones cerradas por reset MFA admin', 'Sesiones se cerraron por modificacion MFA administrativa.', 'critical', 'Confirmar identidad del usuario afectado.'),
    'sessions.revoked_detected_on_request' => $event('Sesiones', 'Sesion revocada detectada', 'Una sesion revocada intento continuar navegando.', 'warning', 'Revisar si se repite desde la misma IP.'),

    'upload.success' => $event('Subidas', 'Archivo subido', 'Un archivo administrativo fue subido correctamente.', 'success', 'Verificar contexto del modulo y tipo de archivo.'),
    'upload.failed_invalid_extension' => $event('Subidas', 'Extension invalida', 'Se rechazo una subida por extension no permitida.', 'warning', 'Revisar intentos de subir scripts o archivos no autorizados.'),
    'upload.failed_invalid_size' => $event('Subidas', 'Tamano invalido', 'Se rechazo una subida por tamano.', 'warning', 'Confirmar limites configurados.'),
    'upload.failed_invalid_mime' => $event('Subidas', 'MIME invalido', 'Se rechazo una subida por tipo MIME no permitido.', 'warning', 'Puede indicar archivo disfrazado o no compatible.'),

    '2fa_disabled' => $event('MFA', '2FA desactivado', 'Se registra cuando un usuario desactiva la verificacion en dos pasos.', 'warning', 'Revisar si la desactivacion fue esperada, especialmente en cuentas administrativas.'),
    '2fa_enabled' => $event('MFA', '2FA activado', 'Se registra cuando un usuario activa la verificacion en dos pasos en su cuenta.', 'success', 'Verificar que la activacion corresponda al usuario esperado.'),
    'access_denied' => $event('Seguridad', 'Acceso denegado', 'Accion heredada registrada cuando un usuario intento acceder a un recurso sin autorizacion.', 'warning', 'Revisar modulo, ruta, usuario, fecha e IP asociados al evento.'),
    'account.email_change_verified' => $event('Mi Cuenta', 'Cambio de correo verificado', 'Se registra cuando el usuario confirma correctamente el codigo de verificacion para cambiar su correo.', 'success', 'Validar que el nuevo correo corresponda al usuario esperado.'),
    'account.sessions_history_viewed' => $event('Mi Cuenta', 'Historial propio de sesiones consultado', 'Se registra cuando un usuario consulta su propio historial de sesiones.', 'info', 'Evento informativo util para seguimiento de actividad de cuenta.'),
    'authentication_settings.update_failed' => $event('Autenticacion', 'Error al actualizar configuracion de autenticacion', 'Se registra cuando fallo un intento de guardar la configuracion de autenticacion.', 'warning', 'Revisar el detalle del error y confirmar que la configuracion no quedo incompleta.'),
    'authentication_settings.updated' => $event('Autenticacion', 'Configuracion de autenticacion actualizada', 'Se registra cuando se actualiza la configuracion general de autenticacion.', 'warning', 'Revisar que opciones fueron modificadas, especialmente login externo, dominios autorizados y creacion automatica de usuarios.'),
    'email_updated' => $event('Mi Cuenta', 'Correo actualizado', 'Accion heredada registrada cuando se actualizo el correo de una cuenta.', 'warning', 'Revisar modulo, descripcion, usuario, fecha e IP para confirmar que el cambio fue autorizado.'),
    'external_login.account_linked' => $event('OAuth', 'Cuenta externa vinculada', 'Se registra cuando una cuenta externa se vincula con un usuario local.', 'success', 'Confirmar que el proveedor externo y el correo corresponden al usuario correcto.'),
    'external_login.account_unlinked' => $event('OAuth', 'Cuenta externa desvinculada', 'Se registra cuando una cuenta externa se desvincula de un usuario local.', 'warning', 'Revisar si la desvinculacion fue solicitada por el usuario o por administracion.'),
    'external_provider.test_started' => $event('OAuth', 'Prueba de proveedor externo iniciada', 'Se registra cuando se inicia una prueba de configuracion de un proveedor externo.', 'info', 'Revisar el resultado posterior de la prueba para confirmar si fue exitosa o fallida.'),
    'local_login.domain_denied' => $event('Autenticacion', 'Login local bloqueado por dominio', 'Se registra cuando un intento de login local usa un correo que no pertenece a los dominios autorizados.', 'warning', 'Revisar si el dominio usado corresponde a un error del usuario o a un intento no autorizado.'),
    'login_2fa_required' => $event('MFA', '2FA requerido en login', 'Se registra cuando el login requiere completar verificacion en dos pasos.', 'info', 'Confirmar que el usuario complete el desafio MFA esperado.'),
    'login_2fa_success' => $event('MFA', '2FA completado en login', 'Se registra cuando el usuario completa correctamente la verificacion en dos pasos durante el login.', 'success', 'Validar IP, horario y navegador si el acceso parece inusual.'),
    'login_failed' => $event('Autenticacion', 'Inicio de sesion fallido', 'Se registra cuando un intento de inicio de sesion no fue exitoso.', 'warning', 'Revisar repeticion de fallos por usuario o IP.'),
    'login_success' => $event('Autenticacion', 'Inicio de sesion exitoso', 'Se registra cuando un usuario inicia sesion correctamente.', 'success', 'Validar IP, horario y navegador si el acceso parece inusual.'),
    'logout' => $event('Autenticacion', 'Cierre de sesion', 'Se registra cuando un usuario cierra sesion.', 'info', 'Usar como referencia para seguimiento de actividad del usuario.'),
    'password_changed' => $event('Mi Cuenta', 'Contrasena cambiada', 'Accion heredada registrada cuando se cambio una contrasena.', 'warning', 'Revisar modulo, descripcion y usuario para identificar si fue cambio propio, recuperacion o administracion.'),
    'password.history_reuse_blocked' => $event('Politica de contrasenas', 'Reutilizacion de contrasena bloqueada', 'Se registra cuando el sistema impide usar una contrasena anteriormente utilizada.', 'warning', 'Revisar si el usuario esta intentando reutilizar credenciales antiguas.'),
    'password.required_change_failed' => $event('Politica de contrasenas', 'Cambio obligatorio de contrasena fallido', 'Se registra cuando falla un intento de cambio obligatorio de contrasena.', 'warning', 'Revisar si fallo por incumplimiento de politica o por error del usuario.'),
    'preferences_updated' => $event('Mi Cuenta', 'Preferencias actualizadas', 'Se registra cuando un usuario actualiza sus preferencias personales.', 'info', 'Revisar si el cambio corresponde a preferencias visuales o de cuenta.'),
    'profile_updated' => $event('Perfil', 'Perfil actualizado', 'Accion heredada registrada cuando se actualizo informacion de perfil.', 'info', 'Revisar descripcion, usuario, fecha e IP si el cambio parece inusual.'),
    'session_locked' => $event('Sesiones', 'Sesion bloqueada', 'Se registra cuando una sesion fue bloqueada, normalmente por inactividad o politica de seguridad.', 'info', 'Revisar si el bloqueo corresponde al comportamiento esperado.'),
    'session_unlocked' => $event('Sesiones', 'Sesion desbloqueada', 'Se registra cuando una sesion bloqueada fue desbloqueada correctamente.', 'success', 'Validar que el desbloqueo haya sido realizado por el usuario legitimo.'),
    'settings_updated' => $event('Configuracion', 'Configuracion actualizada', 'Accion generica registrada cuando se actualiza una configuracion del sistema.', 'info', 'Revisar el modulo y descripcion asociados al evento para identificar que configuracion fue modificada.'),
    'smtp_tested' => $event('SMTP', 'Configuracion SMTP probada', 'Se registra cuando se ejecuta una prueba de envio SMTP.', 'info', 'Revisar el resultado de la prueba para confirmar si el correo fue enviado correctamente.'),
    'theme_updated' => $event('Perfil', 'Tema visual actualizado', 'Se registra cuando un usuario cambia el tema visual del sistema.', 'info', 'Evento informativo, normalmente no requiere accion.'),
    'unlock_failed' => $event('Sesiones', 'Desbloqueo fallido', 'Accion heredada registrada cuando falla el desbloqueo de una sesion o cuenta.', 'warning', 'Revisar usuario, IP y cantidad de intentos fallidos.'),
    'users.sessions_history_viewed' => $event('Usuarios', 'Historial de sesiones de usuario consultado', 'Se registra cuando un administrador consulta el historial de sesiones de un usuario.', 'info', 'Verificar que la consulta corresponda a una necesidad administrativa o de seguridad.'),

    'activated' => $event('Sistema', 'Accion generica: activado', 'Accion generica heredada registrada cuando se activo un registro en el sistema.', 'info', 'Para un analisis preciso, revisar modulo, descripcion, usuario, fecha e IP asociados al evento.'),
    'created' => $event('Sistema', 'Accion generica: creado', 'Accion generica registrada cuando se creo un registro en el sistema.', 'info', 'Para un analisis preciso, revisar el modulo, descripcion, usuario, fecha e IP asociados al evento.'),
    'deactivated' => $event('Sistema', 'Accion generica: desactivado', 'Accion generica heredada registrada cuando se desactivo un registro en el sistema.', 'warning', 'Para un analisis preciso, revisar modulo, descripcion, usuario, fecha e IP asociados al evento.'),
    'deleted' => $event('Sistema', 'Accion generica: eliminado', 'Accion generica registrada cuando se elimino o marco como eliminado un registro en el sistema.', 'warning', 'Para un analisis preciso, revisar el modulo, descripcion, usuario, fecha e IP asociados al evento.'),
    'downloaded' => $event('Sistema', 'Accion generica: descargado', 'Accion generica heredada registrada cuando se descargo un archivo o recurso del sistema.', 'info', 'Para un analisis preciso, revisar modulo, recurso, usuario, fecha e IP asociados al evento.'),
    'exported' => $event('Sistema', 'Accion generica: exportado', 'Accion generica registrada cuando se exportaron registros desde el sistema.', 'warning', 'Para un analisis preciso, revisar el modulo, filtros usados si existen, usuario, fecha e IP asociados al evento.'),
    'permissions_updated' => $event('Sistema', 'Accion generica: permisos actualizados', 'Accion generica heredada registrada cuando se actualizaron permisos.', 'warning', 'Revisar modulo, rol o usuario afectado, descripcion, fecha e IP asociados al evento.'),
    'replaced' => $event('Sistema', 'Accion generica: reemplazado', 'Accion generica heredada registrada cuando se reemplazo un recurso o archivo.', 'warning', 'Para un analisis preciso, revisar modulo, descripcion, usuario, fecha e IP asociados al evento.'),
    'updated' => $event('Sistema', 'Accion generica: actualizado', 'Accion generica registrada cuando se actualizo un registro en el sistema.', 'info', 'Para un analisis preciso, revisar el modulo, descripcion, usuario, fecha e IP asociados al evento.'),
    'uploaded' => $event('Sistema', 'Accion generica: archivo subido', 'Accion generica registrada cuando se subio un archivo al sistema.', 'info', 'Para un analisis preciso, revisar el modulo, nombre del recurso, usuario, fecha e IP asociados al evento.'),

    'system_information.updated' => $event('Informacion del sistema', 'Informacion del sistema actualizada', 'Se actualizo informacion descriptiva del sistema.', 'info', 'Verificar que los datos publicados sean correctos.'),
    'system_health.viewed' => $event('Salud del sistema', 'Panel de salud consultado', 'Un administrador consulto el panel de salud del sistema.', 'info', 'Evento informativo; revisar si hay consultas inusuales o recurrentes.'),
    'maintenance.cleanup_viewed' => $event('Mantenimiento', 'Limpieza consultada', 'Un administrador consulto el resumen de datos temporales limpiables.', 'info', 'Evento informativo para seguimiento administrativo.'),
    'maintenance.cleanup_started' => $event('Mantenimiento', 'Limpieza iniciada', 'Se inicio una limpieza controlada de datos temporales.', 'warning', 'Revisar categorias seleccionadas y retenciones configuradas.'),
    'maintenance.cleanup_completed' => $event('Mantenimiento', 'Limpieza completada', 'La limpieza de datos temporales finalizo.', 'success', 'Verificar cantidades eliminadas por categoria.'),
    'maintenance.cleanup_failed' => $event('Mantenimiento', 'Limpieza fallida', 'Fallo la ejecucion de limpieza de datos temporales.', 'warning', 'Revisar logs tecnicos y categorias seleccionadas.'),
    'maintenance.cleanup.password_reset_tokens' => $event('Mantenimiento', 'Tokens de recuperacion limpiados', 'Se eliminaron tokens vencidos, usados o antiguos de recuperacion de contrasena.', 'warning', 'Confirmar cantidad eliminada; no incluye usuarios ni contrasenas.'),
    'maintenance.cleanup.email_change_codes' => $event('Mantenimiento', 'Codigos de cambio de correo limpiados', 'Se eliminaron codigos vencidos, usados o antiguos de cambio de correo.', 'warning', 'Confirmar cantidad eliminada; no registra codigos ni hashes.'),
    'maintenance.cleanup.revoked_sessions' => $event('Mantenimiento', 'Sesiones revocadas antiguas limpiadas', 'Se eliminaron sesiones revocadas antiguas.', 'warning', 'Confirmar que no se eliminaron sesiones activas.'),
    'maintenance.cleanup.login_attempts' => $event('Mantenimiento', 'Intentos fallidos antiguos limpiados', 'Se eliminaron registros antiguos de intentos de login.', 'warning', 'Confirmar retencion usada para no afectar bloqueos vigentes.'),
    'maintenance.cleanup.password_histories' => $event('Mantenimiento', 'Historial de contrasenas depurado', 'Se eliminaron historiales que exceden la politica configurada.', 'warning', 'Confirmar que se conservaron los ultimos hashes requeridos por usuario.'),
    'maintenance.cleanup.read_notifications' => $event('Mantenimiento', 'Notificaciones leidas antiguas limpiadas', 'Se eliminaron notificaciones internas leidas que exceden la retencion configurada.', 'warning', 'Confirmar que no se eliminaron notificaciones no leidas.'),
    'maintenance.cleanup.logs' => $event('Mantenimiento', 'Logs antiguos limpiados', 'Se eliminaron archivos de log antiguos en rutas permitidas.', 'warning', 'No registra contenido ni rutas absolutas sensibles.'),
    'maintenance.cleanup.temp_files' => $event('Mantenimiento', 'Archivos temporales limpiados', 'Se eliminaron archivos antiguos en carpetas temporales permitidas.', 'warning', 'Confirmar que solo se usaron rutas temporales permitidas.'),
    'notifications.viewed' => $event('Notificaciones', 'Notificaciones consultadas', 'Un usuario consulto su listado de notificaciones internas.', 'info', 'Evento informativo para seguimiento de actividad de cuenta.'),
    'notifications.marked_read' => $event('Notificaciones', 'Notificacion marcada como leida', 'Un usuario marco una notificacion interna como leida.', 'info', 'Verificar solo si se investiga actividad de cuenta.'),
    'notifications.marked_all_read' => $event('Notificaciones', 'Todas las notificaciones marcadas como leidas', 'Un usuario marco todas sus notificaciones internas como leidas.', 'info', 'Evento informativo para seguimiento de actividad de cuenta.'),
    'notifications.created' => $event('Notificaciones', 'Notificacion interna creada', 'El sistema creo una notificacion interna para un usuario.', 'info', 'No debe incluir datos sensibles ni contenido privado innecesario.'),
    'notifications.deleted' => $event('Notificaciones', 'Notificacion eliminada de lista propia', 'Un usuario elimino una notificacion interna de su propia lista.', 'info', 'Confirmar solo si se investiga actividad de cuenta; no implica eliminacion de notificaciones de otros usuarios.'),
    'notifications.deleted_read' => $event('Notificaciones', 'Notificaciones leidas eliminadas de lista propia', 'Un usuario elimino sus notificaciones internas leidas.', 'info', 'Revisar la cantidad eliminada si hay dudas sobre actividad de cuenta.'),
    'notifications.deleted_all' => $event('Notificaciones', 'Todas las notificaciones eliminadas de lista propia', 'Un usuario elimino todas sus notificaciones internas de su lista.', 'info', 'Revisar la cantidad eliminada y confirmar que la accion corresponda al usuario.'),
    'languages.created' => $event('Idiomas', 'Idioma creado', 'Se creo un idioma del sistema.', 'info', 'Verificar que exista archivo de traduccion correspondiente.'),
    'languages.updated' => $event('Idiomas', 'Idioma actualizado', 'Se actualizo un idioma del sistema.', 'info', 'Confirmar codigo, nombre y estado.'),
    'languages.activated' => $event('Idiomas', 'Idioma activado', 'Se activo un idioma.', 'info', 'Verificar disponibilidad de traducciones.'),
    'languages.deactivated' => $event('Idiomas', 'Idioma desactivado', 'Se desactivo un idioma.', 'warning', 'Validar impacto sobre usuarios que lo tenian seleccionado.'),
    'languages.deactivate_denied' => $event('Idiomas', 'Desactivacion de idioma denegada', 'Se intento desactivar un idioma protegido.', 'warning', 'Revisar intento sobre idioma predeterminado.'),
];
